# Generated by Django 5.0.6 on 2024-05-31 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_ramo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramo',
            name='id_ramo',
            field=models.AutoField(db_column='idRamo', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.AutoField(db_column='idSeccion', primary_key=True, serialize=False)),
                ('codigo_seccion', models.CharField(max_length=20)),
                ('id_ramo', models.ForeignKey(db_column='idRamo', on_delete=django.db.models.deletion.CASCADE, to='alumnos.ramo')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoSeccion',
            fields=[
                ('id_alumnoseccion', models.AutoField(db_column='idAlumnoSeccion', primary_key=True, serialize=False)),
                ('id_alumno', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('id_seccion', models.ForeignKey(db_column='idSeccion', on_delete=django.db.models.deletion.CASCADE, to='alumnos.seccion')),
            ],
        ),
    ]
